apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-server-pvc
  labels:
    app: valheim-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

