apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-server-data
  labels:
    app: valheim-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-server-files
  labels:
    app: valheim-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
